imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

swagger:
    version: '2.0'
    info:
        title: '&Frankly sample API'
        version: '1.0.0'
        description: 'Sample API according to test task'
    host: '%api_host%'
    base_path: '/v1'
    schemes:
        - http
#    produces:
#        - application/json
#        - text/csv
#    consumes:
#        - application/json
#        - text/csv
    annotations:
        bundles:
            - AiApiBundle
        paths:
            - "%kernel.root_dir%/../src/Ai/CoreDomain"
            - "%kernel.root_dir%/../src/Ai/CoreDomainBundle/Entity"
#    api_gateway: false