imports:
  - { resource: "@AiCoreDomainBundle/Resources/config/services.yml" }
  - { resource: "@AiApiBundle/Resources/config/services.yml" }
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
